name: Build Tools
description: Build Tools
inputs:
  test:
    required: false
  deploy:
    required: false
runs:
  using: 'composite'
  steps:
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Run tests
      if: ${{ inputs.test == true }}
      run: echo ${{ github.event.pull_request.body }} | ruby launcher.rb test
      shell: bash
    - name: Deploy
      if: ${{ inputs.deploy == true }}
      run: echo ${{ github.event.pull_request.body }} | ruby launcher.rb deploy
      shell: bash
