name: Build Tools
description: Build Tools
inputs:
  action:
    description: 'Command to run: one of [test, deploy, notify_review_requested, notify_pr_approved]'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: ${{ inputs.action }}
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_URL: ${{ github.event.pull_request.url }}
        PR_TITLE: ${{ github.event.pull_request.title }}
      run: |
        cd "${{ github.action_path }}"
        ruby launcher.rb ${{ inputs.action }}
      shell: bash
