name: Build Tools
description: Build Tools
inputs:
  action:
    description: 'Command to run: [test, deploy]'
    type: string
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
    - name: Run tests
      if: ${{ inputs.action == 'test' }}
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_URL: ${{ github.event.pull_request.url }}
      run: |
        cd "${{ github.action_path }}"
        ruby launcher.rb test
      shell: bash
    - name: Deploy to Production
      if: ${{ inputs.action == 'deploy' }}
      env:
        PR_BODY: ${{ github.event.pull_request.body }}
        PR_URL: ${{ github.event.pull_request.url }}
      run: |
        cd "${{ github.action_path }}"
        ruby launcher.rb deploy
      shell: bash
